// Built-in word list for Froggy Phrase generation (~2000 words)
// Includes common English words plus frog-related terms

export const FROG_TERMS = [
  'frog', 'toad', 'tadpole', 'ribbit', 'croak', 'lily', 'pond', 'leap',
  'amphibian', 'bullfrog', 'treefrog', 'pollywog', 'webbed', 'hopper',
  'marsh', 'swamp', 'wetland', 'lilypad', 'spawn', 'metamorphosis'
];

export const WORD_LIST = [
  // Common nouns (animals, nature, objects)
  'apple', 'bear', 'bird', 'boat', 'book', 'bridge', 'butterfly', 'camera', 'candle', 'castle',
  'cat', 'chair', 'cloud', 'coffee', 'compass', 'coral', 'crown', 'crystal', 'desert', 'diamond',
  'dolphin', 'dragon', 'eagle', 'earth', 'elephant', 'emerald', 'falcon', 'feather', 'fire', 'fish',
  'flame', 'flower', 'forest', 'fountain', 'garden', 'glacier', 'gold', 'guitar', 'harbor', 'hawk',
  'heart', 'hill', 'honey', 'horse', 'island', 'jade', 'jewel', 'jungle', 'key', 'kite',
  'lake', 'lamp', 'lantern', 'leaf', 'lemon', 'light', 'lion', 'lotus', 'meadow', 'mirror',
  'moon', 'mountain', 'music', 'nest', 'ocean', 'olive', 'orange', 'orchid', 'owl', 'palace',
  'palm', 'paper', 'parrot', 'path', 'pearl', 'pebble', 'penguin', 'phoenix', 'piano', 'pine',
  'planet', 'prism', 'pyramid', 'quartz', 'rabbit', 'rain', 'rainbow', 'raven', 'reef', 'river',
  'road', 'robin', 'rock', 'rose', 'ruby', 'sail', 'sand', 'sapphire', 'sea', 'seal',
  'shadow', 'shell', 'ship', 'shore', 'silver', 'sky', 'snow', 'song', 'spark', 'spring',
  'star', 'stone', 'storm', 'stream', 'summer', 'sun', 'sunset', 'swan', 'sword', 'temple',
  'thunder', 'tide', 'tiger', 'tower', 'trail', 'treasure', 'tree', 'turtle', 'valley', 'vine',
  'violet', 'volcano', 'water', 'wave', 'whale', 'willow', 'wind', 'window', 'winter', 'wolf',
  
  // Adjectives
  'ancient', 'azure', 'beautiful', 'bold', 'brave', 'bright', 'brilliant', 'calm', 'clear', 'clever',
  'cosmic', 'crimson', 'crystal', 'dancing', 'daring', 'deep', 'distant', 'divine', 'dreaming', 'electric',
  'elegant', 'emerald', 'endless', 'eternal', 'fair', 'faithful', 'fierce', 'flowing', 'flying', 'frozen',
  'gentle', 'giant', 'glowing', 'golden', 'graceful', 'grand', 'great', 'happy', 'hidden', 'holy',
  'honest', 'humble', 'infinite', 'ivory', 'jade', 'joyful', 'kind', 'lasting', 'light', 'little',
  'living', 'lonely', 'lovely', 'loyal', 'lucky', 'magic', 'mighty', 'misty', 'mystic', 'noble',
  'northern', 'peaceful', 'perfect', 'proud', 'pure', 'quiet', 'radiant', 'rapid', 'rising', 'royal',
  'sacred', 'sapphire', 'secret', 'serene', 'shining', 'silent', 'silver', 'simple', 'singing', 'sleeping',
  'small', 'smooth', 'soaring', 'soft', 'southern', 'sparkling', 'steady', 'still', 'strong', 'summer',
  'swift', 'tender', 'timeless', 'tranquil', 'true', 'twilight', 'vast', 'velvet', 'vibrant', 'wandering',
  'warm', 'western', 'white', 'wild', 'wise', 'wondrous', 'young',
  
  // Verbs (present participle form)
  'ascending', 'awakening', 'blazing', 'blooming', 'breathing', 'building', 'burning', 'calling', 'carving', 'chasing',
  'climbing', 'creating', 'crossing', 'dancing', 'drifting', 'dwelling', 'echoing', 'falling', 'finding', 'floating',
  'flowing', 'flying', 'following', 'forging', 'gliding', 'glowing', 'growing', 'guarding', 'guiding', 'healing',
  'hearing', 'hiding', 'holding', 'hoping', 'hunting', 'journeying', 'jumping', 'keeping', 'knowing', 'laughing',
  'leading', 'learning', 'living', 'loving', 'making', 'moving', 'painting', 'passing', 'playing', 'praying',
  'racing', 'resting', 'riding', 'rising', 'roaming', 'running', 'sailing', 'searching', 'seeking', 'shining',
  'singing', 'sleeping', 'soaring', 'speaking', 'standing', 'swimming', 'teaching', 'thinking', 'traveling', 'walking',
  'wandering', 'watching', 'weaving', 'whispering', 'wishing', 'working', 'writing',
  
  // More nouns (abstract concepts, places, things)
  'adventure', 'age', 'air', 'angel', 'answer', 'arrow', 'art', 'autumn', 'balance', 'banner',
  'battle', 'bay', 'beacon', 'beam', 'beauty', 'bell', 'blade', 'blessing', 'bloom', 'blossom',
  'bond', 'border', 'branch', 'breeze', 'canyon', 'cape', 'cascade', 'cave', 'center', 'ceremony',
  'chain', 'chamber', 'champion', 'change', 'channel', 'chapter', 'charm', 'chase', 'choice', 'circle',
  'citadel', 'city', 'cliff', 'coast', 'code', 'comet', 'command', 'courage', 'course', 'cove',
  'craft', 'crest', 'crossing', 'current', 'cycle', 'dance', 'dawn', 'day', 'deed', 'delta',
  'depth', 'destiny', 'distance', 'dome', 'door', 'dove', 'dream', 'dune', 'dusk', 'dust',
  'echo', 'edge', 'empire', 'end', 'energy', 'essence', 'evening', 'faith', 'fall', 'fate',
  'field', 'fjord', 'flash', 'flight', 'force', 'form', 'fort', 'freedom', 'frost', 'future',
  'gate', 'gem', 'gift', 'glen', 'glory', 'grace', 'grain', 'grass', 'grave', 'grove',
  'guard', 'guest', 'guide', 'gulf', 'hall', 'hand', 'haven', 'haven', 'height', 'heir',
  'helm', 'hero', 'highland', 'history', 'home', 'honor', 'hope', 'horizon', 'horn', 'hour',
  'house', 'hymn', 'ice', 'image', 'inn', 'iron', 'journey', 'joy', 'justice', 'keep',
  'keeper', 'kingdom', 'knight', 'knowledge', 'land', 'law', 'legend', 'lesson', 'letter', 'life',
  'line', 'link', 'lore', 'love', 'luck', 'lullaby', 'mage', 'maiden', 'mark', 'master',
  'memory', 'mercy', 'message', 'midnight', 'mind', 'moment', 'monarch', 'morning', 'myth', 'name',
  'nation', 'nature', 'night', 'noon', 'north', 'note', 'oath', 'oasis', 'order', 'origin',
  'page', 'passage', 'past', 'peace', 'peak', 'people', 'place', 'plain', 'plan', 'plateau',
  'poem', 'point', 'portal', 'power', 'prayer', 'present', 'pride', 'prince', 'princess', 'promise',
  'prophecy', 'quest', 'question', 'range', 'realm', 'reason', 'refuge', 'reign', 'relic', 'rest',
  'return', 'ridge', 'rift', 'ring', 'rite', 'ritual', 'root', 'route', 'rune', 'sage',
  'sanctuary', 'sands', 'scale', 'scepter', 'scroll', 'season', 'secret', 'seed', 'sentinel', 'shade',
  'shield', 'shrine', 'side', 'sign', 'silence', 'silk', 'site', 'skill', 'soul', 'sound',
  'source', 'south', 'space', 'spell', 'sphere', 'spirit', 'spire', 'staff', 'stair', 'step',
  'story', 'strength', 'summit', 'sunrise', 'symbol', 'tale', 'task', 'tear', 'terrain', 'test',
  'thread', 'threshold', 'throne', 'time', 'titan', 'token', 'tomb', 'torch', 'touch', 'trade',
  'tradition', 'traveler', 'treaty', 'trial', 'tribe', 'tribute', 'triumph', 'truce', 'trust', 'truth',
  'turn', 'twilight', 'union', 'unity', 'vale', 'valor', 'vault', 'veil', 'venture', 'verse',
  'vessel', 'victory', 'view', 'vigil', 'village', 'vision', 'voice', 'vow', 'voyage', 'wall',
  'warden', 'warrior', 'watch', 'way', 'wealth', 'weapon', 'west', 'whisper', 'will', 'wisdom',
  'wish', 'witness', 'wonder', 'word', 'world', 'worth', 'year', 'zenith', 'zone',
  
  // Additional common words
  'ability', 'above', 'across', 'action', 'after', 'again', 'against', 'ahead', 'alive', 'alone',
  'along', 'always', 'among', 'around', 'away', 'back', 'before', 'behind', 'below', 'beneath',
  'beside', 'between', 'beyond', 'both', 'bottom', 'bound', 'broken', 'built', 'called', 'came',
  'carried', 'caught', 'certain', 'changed', 'chosen', 'close', 'closed', 'cold', 'come', 'coming',
  'common', 'complete', 'cool', 'could', 'covered', 'dark', 'dead', 'decided', 'different', 'direct',
  'done', 'down', 'drawn', 'driven', 'during', 'each', 'early', 'east', 'easy', 'eight',
  'either', 'else', 'empty', 'enough', 'entire', 'equal', 'even', 'ever', 'every', 'exact',
  'except', 'extra', 'face', 'fact', 'failed', 'fallen', 'false', 'family', 'famous', 'far',
  'fast', 'father', 'felt', 'few', 'fifteen', 'fifth', 'fifty', 'filled', 'final', 'fine',
  'finished', 'first', 'five', 'fixed', 'flat', 'followed', 'food', 'foot', 'forever', 'forgot',
  'forgotten', 'former', 'forth', 'forty', 'forward', 'found', 'four', 'fourth', 'free', 'fresh',
  'friend', 'from', 'front', 'full', 'further', 'gave', 'general', 'given', 'goes', 'gone',
  'good', 'got', 'gray', 'green', 'ground', 'group', 'grown', 'had', 'half', 'happened',
  'hard', 'has', 'have', 'having', 'head', 'heard', 'held', 'help', 'helped', 'here',
  'high', 'himself', 'his', 'hold', 'hot', 'hour', 'how', 'however', 'hundred', 'idea',
  'important', 'inside', 'instead', 'into', 'itself', 'joined', 'just', 'kept', 'kind', 'knew',
  'known', 'large', 'last', 'late', 'later', 'lay', 'lead', 'least', 'leave', 'left',
  'less', 'let', 'level', 'lie', 'like', 'likely', 'limited', 'list', 'listen', 'lived',
  'long', 'look', 'looked', 'lost', 'lot', 'low', 'lower', 'made', 'main', 'major',
  'make', 'man', 'many', 'map', 'matter', 'may', 'mean', 'meant', 'meet', 'member',
  'men', 'met', 'middle', 'might', 'mile', 'mind', 'minute', 'miss', 'modern', 'moment',
  'month', 'more', 'morning', 'most', 'mother', 'move', 'moved', 'much', 'must', 'myself',
  'named', 'natural', 'near', 'nearly', 'necessary', 'need', 'needed', 'never', 'new', 'next',
  'nine', 'ninety', 'nobody', 'none', 'nor', 'normal', 'not', 'note', 'nothing', 'notice',
  'now', 'number', 'object', 'off', 'offer', 'office', 'often', 'old', 'once', 'one',
  'only', 'open', 'opened', 'opposite', 'option', 'order', 'ordered', 'original', 'other', 'others',
  'otherwise', 'ought', 'our', 'out', 'outside', 'over', 'own', 'paid', 'pair', 'part',
  'particular', 'party', 'passed', 'past', 'pattern', 'pay', 'per', 'perhaps', 'period', 'person',
  'personal', 'picture', 'piece', 'placed', 'plan', 'plant', 'play', 'please', 'plus', 'point',
  'poor', 'popular', 'position', 'possible', 'pound', 'present', 'president', 'press', 'pressure', 'pretty',
  'previous', 'price', 'private', 'probably', 'problem', 'process', 'produce', 'product', 'program', 'project',
  'proper', 'property', 'protect', 'provide', 'public', 'pull', 'purpose', 'push', 'put', 'quality',
  'quarter', 'question', 'quick', 'quickly', 'quite', 'race', 'raise', 'ran', 'range', 'rate',
  'rather', 'reach', 'reached', 'read', 'ready', 'real', 'really', 'reason', 'receive', 'recent',
  'record', 'red', 'reduce', 'regard', 'region', 'regular', 'related', 'remain', 'remember', 'removed',
  'report', 'represent', 'require', 'research', 'resource', 'respect', 'rest', 'result', 'return', 'reveal',
  'right', 'rise', 'risk', 'river', 'road', 'rock', 'role', 'roll', 'room', 'round',
  'rule', 'run', 'safe', 'said', 'same', 'sat', 'save', 'saw', 'say', 'scene',
  'school', 'science', 'sea', 'season', 'seat', 'second', 'section', 'see', 'seem', 'seemed',
  'seen', 'self', 'sell', 'send', 'sense', 'sent', 'separate', 'series', 'serious', 'serve',
  'service', 'set', 'settle', 'seven', 'seventy', 'several', 'shall', 'shape', 'share', 'she',
  'ship', 'short', 'shot', 'should', 'show', 'shown', 'side', 'sign', 'significant', 'similar',
  'simple', 'simply', 'since', 'single', 'sister', 'sit', 'site', 'situation', 'six', 'sixty',
  'size', 'slow', 'small', 'social', 'society', 'soft', 'sold', 'soldier', 'some', 'somebody',
  'somehow', 'someone', 'something', 'sometimes', 'somewhat', 'somewhere', 'son', 'soon', 'sort', 'sought',
  'sound', 'south', 'space', 'speak', 'special', 'specific', 'spent', 'spoke', 'spot', 'spread',
  'spring', 'square', 'stage', 'stand', 'standard', 'star', 'start', 'started', 'state', 'statement',
  'station', 'stay', 'step', 'still', 'stock', 'stood', 'stop', 'stopped', 'store', 'story',
  'straight', 'strange', 'street', 'strength', 'strike', 'strong', 'structure', 'student', 'study', 'stuff',
  'subject', 'success', 'such', 'sudden', 'suddenly', 'suffer', 'suggest', 'suit', 'summer', 'sun',
  'supply', 'support', 'suppose', 'sure', 'surface', 'system', 'table', 'take', 'taken', 'talk',
  'tax', 'teach', 'teacher', 'team', 'tell', 'ten', 'tend', 'term', 'test', 'than',
  'thank', 'that', 'the', 'their', 'them', 'themselves', 'then', 'theory', 'there', 'therefore',
  'these', 'they', 'thing', 'think', 'third', 'thirty', 'this', 'those', 'though', 'thought',
  'thousand', 'three', 'through', 'throughout', 'throw', 'thus', 'till', 'time', 'today', 'together',
  'told', 'tomorrow', 'tonight', 'too', 'took', 'top', 'total', 'touch', 'toward', 'town',
  'trade', 'train', 'travel', 'treat', 'treatment', 'tree', 'trial', 'trip', 'trouble', 'true',
  'try', 'turn', 'turned', 'twelve', 'twenty', 'two', 'type', 'under', 'understand', 'unit',
  'united', 'until', 'up', 'upon', 'use', 'used', 'usual', 'usually', 'value', 'various',
  'very', 'view', 'village', 'visit', 'voice', 'vote', 'wait', 'walk', 'wall', 'want',
  'war', 'warm', 'was', 'watch', 'water', 'way', 'we', 'wear', 'week', 'weight',
  'well', 'went', 'were', 'west', 'what', 'whatever', 'when', 'where', 'whether', 'which',
  'while', 'white', 'who', 'whole', 'whom', 'whose', 'why', 'wide', 'wife', 'will',
  'win', 'wind', 'window', 'wish', 'with', 'within', 'without', 'woman', 'women', 'won',
  'wonder', 'wood', 'word', 'work', 'worked', 'worker', 'world', 'would', 'write', 'written',
  'wrong', 'wrote', 'yard', 'yeah', 'year', 'yes', 'yet', 'you', 'young', 'your',
  'yourself', 'youth',
  
  // Include frog terms in the main list
  ...FROG_TERMS
];

// Ensure we have at least 2000 unique words
export const UNIQUE_WORDS = Array.from(new Set(WORD_LIST));
