/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Visibility = IDL.Variant({
  'privateVisibility' : IDL.Null,
  'publicVisibility' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'joinedPonds' : IDL.Vec(IDL.Text),
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Pond = IDL.Record({
  'associatedTags' : IDL.Vec(IDL.Text),
  'members' : IDL.Vec(IDL.Principal),
  'admin' : IDL.Principal,
  'lilyCount' : IDL.Nat,
  'profileImage' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'memberCount' : IDL.Nat,
  'description' : IDL.Text,
  'bannerImage' : IDL.Opt(ExternalBlob),
  'image' : IDL.Opt(ExternalBlob),
  'moderators' : IDL.Vec(IDL.Principal),
  'visibility' : Visibility,
  'rules' : IDL.Vec(IDL.Text),
});
export const Post = IDL.Record({
  'id' : IDL.Text,
  'tag' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'content' : IDL.Text,
  'username' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'pond' : IDL.Text,
  'viewCount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'image' : IDL.Opt(ExternalBlob),
});
export const Ribbit = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'username' : IDL.Text,
  'timestamp' : IDL.Int,
  'parentId' : IDL.Opt(IDL.Text),
  'postId' : IDL.Text,
});
export const ViewIncrementResult = IDL.Variant({
  'error' : IDL.Null,
  'notFound' : IDL.Null,
  'success' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addModerator' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'addPondRule' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRoleByPhraseHash' : IDL.Func([IDL.Text, UserRole], [], []),
  'canChangeUsername' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'canChangeUsernameByPhraseHash' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'createPond' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, ExternalBlob, ExternalBlob, IDL.Text],
      [],
      [],
    ),
  'editPondSettings' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(Visibility)],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanonicalTagForTag' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getPond' : IDL.Func([IDL.Text], [IDL.Opt(Pond)], ['query']),
  'getPondModerators' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getPondRules' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getPostsByUsername' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'getRibbitsByUsername' : IDL.Func([IDL.Text], [IDL.Vec(Ribbit)], ['query']),
  'getTagRedirects' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileByPhraseHash' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRoleByPhraseHash' : IDL.Func([IDL.Text], [UserRole], ['query']),
  'incrementLilyViewCount' : IDL.Func([IDL.Text], [ViewIncrementResult], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'initializeFroggyPhrase' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPondAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isUserAdminByPhraseHash' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isUsernameAvailableByPhraseHash' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'listPonds' : IDL.Func([], [IDL.Vec(Pond)], ['query']),
  'mergeSimilarTags' : IDL.Func([], [], []),
  'recordUsernameChange' : IDL.Func([IDL.Text], [], []),
  'recordUsernameChangeByPhraseHash' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'registerUsername' : IDL.Func([IDL.Text], [], []),
  'registerUsernameWithPhraseHash' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'releaseUsername' : IDL.Func([IDL.Text], [], []),
  'releaseUsernameWithPhraseHash' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeModerator' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'removePondRule' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserProfileByPhraseHash' : IDL.Func([IDL.Text, UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Visibility = IDL.Variant({
    'privateVisibility' : IDL.Null,
    'publicVisibility' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'joinedPonds' : IDL.Vec(IDL.Text),
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Pond = IDL.Record({
    'associatedTags' : IDL.Vec(IDL.Text),
    'members' : IDL.Vec(IDL.Principal),
    'admin' : IDL.Principal,
    'lilyCount' : IDL.Nat,
    'profileImage' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'memberCount' : IDL.Nat,
    'description' : IDL.Text,
    'bannerImage' : IDL.Opt(ExternalBlob),
    'image' : IDL.Opt(ExternalBlob),
    'moderators' : IDL.Vec(IDL.Principal),
    'visibility' : Visibility,
    'rules' : IDL.Vec(IDL.Text),
  });
  const Post = IDL.Record({
    'id' : IDL.Text,
    'tag' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'content' : IDL.Text,
    'username' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'pond' : IDL.Text,
    'viewCount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'image' : IDL.Opt(ExternalBlob),
  });
  const Ribbit = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'username' : IDL.Text,
    'timestamp' : IDL.Int,
    'parentId' : IDL.Opt(IDL.Text),
    'postId' : IDL.Text,
  });
  const ViewIncrementResult = IDL.Variant({
    'error' : IDL.Null,
    'notFound' : IDL.Null,
    'success' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addModerator' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'addPondRule' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRoleByPhraseHash' : IDL.Func([IDL.Text, UserRole], [], []),
    'canChangeUsername' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'canChangeUsernameByPhraseHash' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'createPond' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          ExternalBlob,
          ExternalBlob,
          IDL.Text,
        ],
        [],
        [],
      ),
    'editPondSettings' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(Visibility)],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanonicalTagForTag' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getPond' : IDL.Func([IDL.Text], [IDL.Opt(Pond)], ['query']),
    'getPondModerators' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getPondRules' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getPostsByUsername' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'getRibbitsByUsername' : IDL.Func([IDL.Text], [IDL.Vec(Ribbit)], ['query']),
    'getTagRedirects' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileByPhraseHash' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRoleByPhraseHash' : IDL.Func([IDL.Text], [UserRole], ['query']),
    'incrementLilyViewCount' : IDL.Func([IDL.Text], [ViewIncrementResult], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'initializeFroggyPhrase' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPondAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isUserAdminByPhraseHash' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isUsernameAvailableByPhraseHash' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'listPonds' : IDL.Func([], [IDL.Vec(Pond)], ['query']),
    'mergeSimilarTags' : IDL.Func([], [], []),
    'recordUsernameChange' : IDL.Func([IDL.Text], [], []),
    'recordUsernameChangeByPhraseHash' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'registerUsername' : IDL.Func([IDL.Text], [], []),
    'registerUsernameWithPhraseHash' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'releaseUsername' : IDL.Func([IDL.Text], [], []),
    'releaseUsernameWithPhraseHash' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeModerator' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'removePondRule' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveUserProfileByPhraseHash' : IDL.Func([IDL.Text, UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };