/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Visibility = IDL.Variant({
  'privateVisibility' : IDL.Null,
  'publicVisibility' : IDL.Null,
});
export const ActivityType = IDL.Variant({
  'like' : IDL.Null,
  'post' : IDL.Null,
  'ribbit' : IDL.Null,
  'viewRibbit' : IDL.Null,
});
export const Activity = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'pond' : IDL.Text,
  'type' : ActivityType,
  'timestamp' : IDL.Int,
  'targetId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'joinedPonds' : IDL.Vec(IDL.Text),
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Post = IDL.Record({
  'id' : IDL.Text,
  'tag' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'content' : IDL.Text,
  'username' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'pond' : IDL.Text,
  'viewCount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'image' : IDL.Opt(ExternalBlob),
});
export const TagStats = IDL.Record({
  'id' : IDL.Text,
  'firstUsedAt' : IDL.Int,
  'repliesTotal' : IDL.Nat,
  'postsTotal' : IDL.Nat,
  'lastActivityAt' : IDL.Int,
});
export const Pond = IDL.Record({
  'associatedTags' : IDL.Vec(IDL.Text),
  'members' : IDL.Vec(IDL.Principal),
  'admin' : IDL.Principal,
  'lilyCount' : IDL.Nat,
  'profileImage' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'memberCount' : IDL.Nat,
  'description' : IDL.Text,
  'bannerImage' : IDL.Opt(ExternalBlob),
  'image' : IDL.Opt(ExternalBlob),
  'moderators' : IDL.Vec(IDL.Principal),
  'visibility' : Visibility,
  'rules' : IDL.Vec(IDL.Text),
});
export const Ribbit = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'username' : IDL.Text,
  'timestamp' : IDL.Int,
  'parentId' : IDL.Opt(IDL.Text),
  'postId' : IDL.Text,
});
export const ViewIncrementResult = IDL.Variant({
  'error' : IDL.Null,
  'notFound' : IDL.Null,
  'success' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addModerator' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'addPondRule' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canChangeUsername' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'clearPostLikes' : IDL.Func([IDL.Text], [], []),
  'createPond' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, ExternalBlob, ExternalBlob, IDL.Text],
      [],
      [],
    ),
  'createPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Text],
      [],
    ),
  'createRibbit' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteLily' : IDL.Func([IDL.Text], [], []),
  'deleteRibbit' : IDL.Func([IDL.Text], [], []),
  'editPondSettings' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(Visibility)],
      [],
      [],
    ),
  'getAllRecentActivities' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanonicalTagForTag' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getJoinedPonds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getLikeCountForPost' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getLiliesByTag' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Post)], ['query']),
  'getNewestTags' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, TagStats))],
      ['query'],
    ),
  'getPond' : IDL.Func([IDL.Text], [IDL.Opt(Pond)], ['query']),
  'getPondAboutInfo' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'title' : IDL.Text,
            'associatedTags' : IDL.Vec(IDL.Text),
            'admin' : IDL.Principal,
            'lilyCount' : IDL.Nat,
            'profileImage' : IDL.Opt(ExternalBlob),
            'name' : IDL.Text,
            'createdAt' : IDL.Int,
            'memberCount' : IDL.Nat,
            'description' : IDL.Text,
            'bannerImage' : IDL.Opt(ExternalBlob),
            'moderators' : IDL.Vec(IDL.Principal),
            'visibility' : Visibility,
            'rules' : IDL.Vec(IDL.Text),
          })
        ),
      ],
      ['query'],
    ),
  'getPondModerators' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getPondRules' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getPost' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
  'getPostLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getPostsByUsername' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'getRecentPosts' : IDL.Func([IDL.Nat], [IDL.Vec(Activity)], ['query']),
  'getRecentRibbitViews' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  'getRecentRibbits' : IDL.Func([IDL.Nat], [IDL.Vec(Activity)], ['query']),
  'getRecentlyLikedPosts' : IDL.Func([IDL.Nat], [IDL.Vec(Activity)], ['query']),
  'getRibbit' : IDL.Func([IDL.Text], [IDL.Opt(Ribbit)], ['query']),
  'getRibbitCountForPost' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getRibbitLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getRibbitsByUsername' : IDL.Func([IDL.Text], [IDL.Vec(Ribbit)], ['query']),
  'getSubcategoriesForTag' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getTagRank' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'tag' : IDL.Text,
          'rank' : IDL.Opt(IDL.Nat),
          'canonicalTag' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getTagRedirects' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getTagStatsForTag' : IDL.Func([IDL.Text], [IDL.Opt(TagStats)], ['query']),
  'getTagSuggestions' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getThreadedRibbitsSorted' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Ribbit)],
      ['query'],
    ),
  'getTopTags' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, TagStats))],
      ['query'],
    ),
  'getTrendingTags' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, TagStats))],
      ['query'],
    ),
  'getUserAvatarByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getViewCountForPost' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'hasUserLikedPost' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'hasUserLikedRibbit' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'incrementLilyViewCount' : IDL.Func([IDL.Text], [ViewIncrementResult], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPondAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'joinPond' : IDL.Func([IDL.Text], [], []),
  'leavePond' : IDL.Func([IDL.Text], [], []),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'likeRibbit' : IDL.Func([IDL.Text], [], []),
  'listPonds' : IDL.Func([], [IDL.Vec(Pond)], ['query']),
  'listPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'listRibbits' : IDL.Func([IDL.Text], [IDL.Vec(Ribbit)], ['query']),
  'mergeSimilarTags' : IDL.Func([], [], []),
  'recordUsernameChange' : IDL.Func([IDL.Text], [], []),
  'registerUsername' : IDL.Func([IDL.Text], [], []),
  'releaseUsername' : IDL.Func([IDL.Text], [], []),
  'removeMemberFromPond' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'removeModerator' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'removePondRule' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPonds' : IDL.Func([IDL.Text], [IDL.Vec(Pond)], ['query']),
  'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'unlikePost' : IDL.Func([IDL.Text], [], []),
  'unlikeRibbit' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Visibility = IDL.Variant({
    'privateVisibility' : IDL.Null,
    'publicVisibility' : IDL.Null,
  });
  const ActivityType = IDL.Variant({
    'like' : IDL.Null,
    'post' : IDL.Null,
    'ribbit' : IDL.Null,
    'viewRibbit' : IDL.Null,
  });
  const Activity = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'pond' : IDL.Text,
    'type' : ActivityType,
    'timestamp' : IDL.Int,
    'targetId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'joinedPonds' : IDL.Vec(IDL.Text),
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Post = IDL.Record({
    'id' : IDL.Text,
    'tag' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'content' : IDL.Text,
    'username' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'pond' : IDL.Text,
    'viewCount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'image' : IDL.Opt(ExternalBlob),
  });
  const TagStats = IDL.Record({
    'id' : IDL.Text,
    'firstUsedAt' : IDL.Int,
    'repliesTotal' : IDL.Nat,
    'postsTotal' : IDL.Nat,
    'lastActivityAt' : IDL.Int,
  });
  const Pond = IDL.Record({
    'associatedTags' : IDL.Vec(IDL.Text),
    'members' : IDL.Vec(IDL.Principal),
    'admin' : IDL.Principal,
    'lilyCount' : IDL.Nat,
    'profileImage' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'memberCount' : IDL.Nat,
    'description' : IDL.Text,
    'bannerImage' : IDL.Opt(ExternalBlob),
    'image' : IDL.Opt(ExternalBlob),
    'moderators' : IDL.Vec(IDL.Principal),
    'visibility' : Visibility,
    'rules' : IDL.Vec(IDL.Text),
  });
  const Ribbit = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'username' : IDL.Text,
    'timestamp' : IDL.Int,
    'parentId' : IDL.Opt(IDL.Text),
    'postId' : IDL.Text,
  });
  const ViewIncrementResult = IDL.Variant({
    'error' : IDL.Null,
    'notFound' : IDL.Null,
    'success' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addModerator' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'addPondRule' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canChangeUsername' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'clearPostLikes' : IDL.Func([IDL.Text], [], []),
    'createPond' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          ExternalBlob,
          ExternalBlob,
          IDL.Text,
        ],
        [],
        [],
      ),
    'createPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'createRibbit' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteLily' : IDL.Func([IDL.Text], [], []),
    'deleteRibbit' : IDL.Func([IDL.Text], [], []),
    'editPondSettings' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(Visibility)],
        [],
        [],
      ),
    'getAllRecentActivities' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanonicalTagForTag' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getJoinedPonds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getLikeCountForPost' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getLiliesByTag' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'getNewestTags' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, TagStats))],
        ['query'],
      ),
    'getPond' : IDL.Func([IDL.Text], [IDL.Opt(Pond)], ['query']),
    'getPondAboutInfo' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'title' : IDL.Text,
              'associatedTags' : IDL.Vec(IDL.Text),
              'admin' : IDL.Principal,
              'lilyCount' : IDL.Nat,
              'profileImage' : IDL.Opt(ExternalBlob),
              'name' : IDL.Text,
              'createdAt' : IDL.Int,
              'memberCount' : IDL.Nat,
              'description' : IDL.Text,
              'bannerImage' : IDL.Opt(ExternalBlob),
              'moderators' : IDL.Vec(IDL.Principal),
              'visibility' : Visibility,
              'rules' : IDL.Vec(IDL.Text),
            })
          ),
        ],
        ['query'],
      ),
    'getPondModerators' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getPondRules' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getPost' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
    'getPostLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getPostsByUsername' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'getRecentPosts' : IDL.Func([IDL.Nat], [IDL.Vec(Activity)], ['query']),
    'getRecentRibbitViews' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'getRecentRibbits' : IDL.Func([IDL.Nat], [IDL.Vec(Activity)], ['query']),
    'getRecentlyLikedPosts' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'getRibbit' : IDL.Func([IDL.Text], [IDL.Opt(Ribbit)], ['query']),
    'getRibbitCountForPost' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getRibbitLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getRibbitsByUsername' : IDL.Func([IDL.Text], [IDL.Vec(Ribbit)], ['query']),
    'getSubcategoriesForTag' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getTagRank' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'tag' : IDL.Text,
            'rank' : IDL.Opt(IDL.Nat),
            'canonicalTag' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getTagRedirects' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getTagStatsForTag' : IDL.Func([IDL.Text], [IDL.Opt(TagStats)], ['query']),
    'getTagSuggestions' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getThreadedRibbitsSorted' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Ribbit)],
        ['query'],
      ),
    'getTopTags' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, TagStats))],
        ['query'],
      ),
    'getTrendingTags' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, TagStats))],
        ['query'],
      ),
    'getUserAvatarByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getViewCountForPost' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'hasUserLikedPost' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'hasUserLikedRibbit' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'incrementLilyViewCount' : IDL.Func([IDL.Text], [ViewIncrementResult], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPondAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'joinPond' : IDL.Func([IDL.Text], [], []),
    'leavePond' : IDL.Func([IDL.Text], [], []),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'likeRibbit' : IDL.Func([IDL.Text], [], []),
    'listPonds' : IDL.Func([], [IDL.Vec(Pond)], ['query']),
    'listPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'listRibbits' : IDL.Func([IDL.Text], [IDL.Vec(Ribbit)], ['query']),
    'mergeSimilarTags' : IDL.Func([], [], []),
    'recordUsernameChange' : IDL.Func([IDL.Text], [], []),
    'registerUsername' : IDL.Func([IDL.Text], [], []),
    'releaseUsername' : IDL.Func([IDL.Text], [], []),
    'removeMemberFromPond' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'removeModerator' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'removePondRule' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPonds' : IDL.Func([IDL.Text], [IDL.Vec(Pond)], ['query']),
    'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'unlikePost' : IDL.Func([IDL.Text], [], []),
    'unlikeRibbit' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };