/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : string,
  'username' : string,
  'pond' : string,
  'type' : ActivityType,
  'timestamp' : bigint,
  'targetId' : string,
}
export type ActivityType = { 'like' : null } |
  { 'post' : null } |
  { 'ribbit' : null } |
  { 'viewRibbit' : null };
export type ExternalBlob = Uint8Array;
export interface Pond {
  'associatedTags' : Array<string>,
  'members' : Array<Principal>,
  'admin' : Principal,
  'lilyCount' : bigint,
  'profileImage' : [] | [ExternalBlob],
  'name' : string,
  'createdAt' : bigint,
  'memberCount' : bigint,
  'description' : string,
  'bannerImage' : [] | [ExternalBlob],
  'image' : [] | [ExternalBlob],
  'moderators' : Array<Principal>,
  'visibility' : Visibility,
  'rules' : Array<string>,
}
export interface Post {
  'id' : string,
  'tag' : [] | [string],
  'title' : string,
  'content' : string,
  'username' : string,
  'link' : [] | [string],
  'pond' : string,
  'viewCount' : bigint,
  'timestamp' : bigint,
  'image' : [] | [ExternalBlob],
}
export interface Ribbit {
  'id' : string,
  'content' : string,
  'username' : string,
  'timestamp' : bigint,
  'parentId' : [] | [string],
  'postId' : string,
}
export interface TagStats {
  'id' : string,
  'firstUsedAt' : bigint,
  'repliesTotal' : bigint,
  'postsTotal' : bigint,
  'lastActivityAt' : bigint,
}
export interface UserProfile {
  'name' : string,
  'joinedPonds' : Array<string>,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type ViewIncrementResult = { 'error' : null } |
  { 'notFound' : null } |
  { 'success' : null };
export type Visibility = { 'privateVisibility' : null } |
  { 'publicVisibility' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addModerator' : ActorMethod<[string, Principal], undefined>,
  'addPondRule' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'canChangeUsername' : ActorMethod<[string], boolean>,
  'clearPostLikes' : ActorMethod<[string], undefined>,
  'createPond' : ActorMethod<
    [string, string, ExternalBlob, ExternalBlob, ExternalBlob, string],
    undefined
  >,
  'createPost' : ActorMethod<
    [
      string,
      string,
      [] | [ExternalBlob],
      [] | [string],
      string,
      string,
      [] | [string],
    ],
    string
  >,
  'createRibbit' : ActorMethod<[string, [] | [string], string, string], string>,
  'deleteLily' : ActorMethod<[string], undefined>,
  'deleteRibbit' : ActorMethod<[string], undefined>,
  'editPondSettings' : ActorMethod<
    [string, [] | [string], [] | [string], [] | [Visibility]],
    undefined
  >,
  'getAllRecentActivities' : ActorMethod<[bigint], Array<Activity>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCanonicalTagForTag' : ActorMethod<[string], string>,
  'getJoinedPonds' : ActorMethod<[], Array<string>>,
  'getLikeCountForPost' : ActorMethod<[string], bigint>,
  'getLiliesByTag' : ActorMethod<[string, string], Array<Post>>,
  'getNewestTags' : ActorMethod<[bigint], Array<[string, TagStats]>>,
  'getPond' : ActorMethod<[string], [] | [Pond]>,
  'getPondAboutInfo' : ActorMethod<
    [string],
    [] | [
      {
        'title' : string,
        'associatedTags' : Array<string>,
        'admin' : Principal,
        'lilyCount' : bigint,
        'profileImage' : [] | [ExternalBlob],
        'name' : string,
        'createdAt' : bigint,
        'memberCount' : bigint,
        'description' : string,
        'bannerImage' : [] | [ExternalBlob],
        'moderators' : Array<Principal>,
        'visibility' : Visibility,
        'rules' : Array<string>,
      }
    ]
  >,
  'getPondModerators' : ActorMethod<[string], Array<Principal>>,
  'getPondRules' : ActorMethod<[string], Array<string>>,
  'getPost' : ActorMethod<[string], [] | [Post]>,
  'getPostLikeCount' : ActorMethod<[string], bigint>,
  'getPostsByUsername' : ActorMethod<[string], Array<Post>>,
  'getRecentPosts' : ActorMethod<[bigint], Array<Activity>>,
  'getRecentRibbitViews' : ActorMethod<[string, bigint], Array<Activity>>,
  'getRecentRibbits' : ActorMethod<[bigint], Array<Activity>>,
  'getRecentlyLikedPosts' : ActorMethod<[bigint], Array<Activity>>,
  'getRibbit' : ActorMethod<[string], [] | [Ribbit]>,
  'getRibbitCountForPost' : ActorMethod<[string], bigint>,
  'getRibbitLikeCount' : ActorMethod<[string], bigint>,
  'getRibbitsByUsername' : ActorMethod<[string], Array<Ribbit>>,
  'getTagRank' : ActorMethod<
    [string],
    { 'tag' : string, 'rank' : [] | [bigint], 'canonicalTag' : string }
  >,
  'getTagRedirects' : ActorMethod<[], Array<[string, string]>>,
  'getTagStatsForTag' : ActorMethod<[string], [] | [TagStats]>,
  'getTagSuggestions' : ActorMethod<[string, bigint], Array<string>>,
  'getThreadedRibbitsSorted' : ActorMethod<[string, string], Array<Ribbit>>,
  'getTopTags' : ActorMethod<[bigint], Array<[string, TagStats]>>,
  'getTrendingTags' : ActorMethod<[bigint], Array<[string, TagStats]>>,
  'getUserAvatarByUsername' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfileByUsername' : ActorMethod<[string], [] | [UserProfile]>,
  'getViewCountForPost' : ActorMethod<[string], bigint>,
  'hasUserLikedPost' : ActorMethod<[string], boolean>,
  'hasUserLikedRibbit' : ActorMethod<[string], boolean>,
  'incrementLilyViewCount' : ActorMethod<[string], ViewIncrementResult>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPondAdmin' : ActorMethod<[string], boolean>,
  'isUsernameAvailable' : ActorMethod<[string], boolean>,
  'joinPond' : ActorMethod<[string], undefined>,
  'leavePond' : ActorMethod<[string], undefined>,
  'likePost' : ActorMethod<[string], undefined>,
  'likeRibbit' : ActorMethod<[string], undefined>,
  'listPonds' : ActorMethod<[], Array<Pond>>,
  'listPosts' : ActorMethod<[], Array<Post>>,
  'listRibbits' : ActorMethod<[string], Array<Ribbit>>,
  'mergeSimilarTags' : ActorMethod<[], undefined>,
  'recordUsernameChange' : ActorMethod<[string], undefined>,
  'registerUsername' : ActorMethod<[string], undefined>,
  'releaseUsername' : ActorMethod<[string], undefined>,
  'removeMemberFromPond' : ActorMethod<[string, Principal], undefined>,
  'removeModerator' : ActorMethod<[string, Principal], undefined>,
  'removePondRule' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPonds' : ActorMethod<[string], Array<Pond>>,
  'searchPosts' : ActorMethod<[string], Array<Post>>,
  'unlikePost' : ActorMethod<[string], undefined>,
  'unlikeRibbit' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];