/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Pond {
  'associatedTags' : Array<string>,
  'members' : Array<Principal>,
  'admin' : Principal,
  'lilyCount' : bigint,
  'profileImage' : [] | [ExternalBlob],
  'name' : string,
  'createdAt' : bigint,
  'memberCount' : bigint,
  'description' : string,
  'bannerImage' : [] | [ExternalBlob],
  'image' : [] | [ExternalBlob],
  'moderators' : Array<Principal>,
  'visibility' : Visibility,
  'rules' : Array<string>,
}
export interface Post {
  'id' : string,
  'tag' : [] | [string],
  'title' : string,
  'content' : string,
  'username' : string,
  'link' : [] | [string],
  'pond' : string,
  'viewCount' : bigint,
  'timestamp' : bigint,
  'image' : [] | [ExternalBlob],
}
export interface Ribbit {
  'id' : string,
  'content' : string,
  'username' : string,
  'timestamp' : bigint,
  'parentId' : [] | [string],
  'postId' : string,
}
export interface UserProfile {
  'name' : string,
  'joinedPonds' : Array<string>,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type ViewIncrementResult = { 'error' : null } |
  { 'notFound' : null } |
  { 'success' : null };
export type Visibility = { 'privateVisibility' : null } |
  { 'publicVisibility' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addModerator' : ActorMethod<[string, Principal], undefined>,
  'addPondRule' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRoleByPhraseHash' : ActorMethod<[string, UserRole], undefined>,
  'canChangeUsername' : ActorMethod<[string], boolean>,
  'canChangeUsernameByPhraseHash' : ActorMethod<[string, string], boolean>,
  'createPond' : ActorMethod<
    [string, string, ExternalBlob, ExternalBlob, ExternalBlob, string],
    undefined
  >,
  'editPondSettings' : ActorMethod<
    [string, [] | [string], [] | [string], [] | [Visibility]],
    undefined
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCanonicalTagForTag' : ActorMethod<[string], string>,
  'getPond' : ActorMethod<[string], [] | [Pond]>,
  'getPondModerators' : ActorMethod<[string], Array<Principal>>,
  'getPondRules' : ActorMethod<[string], Array<string>>,
  'getPostsByUsername' : ActorMethod<[string], Array<Post>>,
  'getRibbitsByUsername' : ActorMethod<[string], Array<Ribbit>>,
  'getTagRedirects' : ActorMethod<[], Array<[string, string]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfileByPhraseHash' : ActorMethod<[string], [] | [UserProfile]>,
  'getUserProfileByUsername' : ActorMethod<[string], [] | [UserProfile]>,
  'getUserRoleByPhraseHash' : ActorMethod<[string], UserRole>,
  'incrementLilyViewCount' : ActorMethod<[string], ViewIncrementResult>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'initializeFroggyPhrase' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPondAdmin' : ActorMethod<[string], boolean>,
  'isUserAdminByPhraseHash' : ActorMethod<[string], boolean>,
  'isUsernameAvailable' : ActorMethod<[string], boolean>,
  'isUsernameAvailableByPhraseHash' : ActorMethod<[string, string], boolean>,
  'listPonds' : ActorMethod<[], Array<Pond>>,
  'mergeSimilarTags' : ActorMethod<[], undefined>,
  'recordUsernameChange' : ActorMethod<[string], undefined>,
  'recordUsernameChangeByPhraseHash' : ActorMethod<[string, string], undefined>,
  'registerUsername' : ActorMethod<[string], undefined>,
  'registerUsernameWithPhraseHash' : ActorMethod<[string, string], undefined>,
  'releaseUsername' : ActorMethod<[string], undefined>,
  'releaseUsernameWithPhraseHash' : ActorMethod<[string, string], undefined>,
  'removeModerator' : ActorMethod<[string, Principal], undefined>,
  'removePondRule' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveUserProfileByPhraseHash' : ActorMethod<[string, UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];