/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Activity {
    id: string;
    username: string;
    pond: string;
    type: ActivityType;
    timestamp: bigint;
    targetId: string;
}
export interface Pond {
    title: string;
    associatedTags: Array<string>;
    members: Array<Principal>;
    admin: Principal;
    lilyCount: bigint;
    profileImage?: ExternalBlob;
    name: string;
    createdAt: bigint;
    memberCount: bigint;
    description: string;
    bannerImage?: ExternalBlob;
    image?: ExternalBlob;
    moderators: Array<Principal>;
    visibility: Visibility;
    rules: Array<string>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Post {
    id: string;
    tag?: string;
    title: string;
    content: string;
    username: string;
    link?: string;
    pond: string;
    viewCount: bigint;
    timestamp: bigint;
    image?: ExternalBlob;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProfile {
    name: string;
    joinedPonds: Array<string>;
    avatar?: ExternalBlob;
}
export interface Ribbit {
    id: string;
    content: string;
    username: string;
    timestamp: bigint;
    parentId?: string;
    postId: string;
}
export enum ActivityType {
    like = "like",
    post = "post",
    ribbit = "ribbit",
    viewRibbit = "viewRibbit"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Visibility {
    privateVisibility = "privateVisibility",
    publicVisibility = "publicVisibility"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addModerator(pondName: string, moderator: Principal): Promise<void>;
    addPondRule(pondName: string, rule: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    canChangeUsername(username: string): Promise<boolean>;
    clearPostLikes(postId: string): Promise<void>;
    createPond(name: string, title: string, description: string, image: ExternalBlob, profileImage: ExternalBlob, bannerImage: ExternalBlob, froggyPhrase: string): Promise<void>;
    createPost(title: string, content: string, image: ExternalBlob | null, link: string | null, pond: string, username: string, tag: string | null): Promise<string>;
    createRibbit(postId: string, parentId: string | null, content: string, username: string): Promise<string>;
    deleteLily(postId: string): Promise<void>;
    deleteRibbit(ribbitId: string): Promise<void>;
    editPondSettings(pondName: string, title: string | null, description: string | null, visibility: Visibility | null): Promise<void>;
    getAllRecentActivities(limit: bigint): Promise<Array<Activity>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCanonicalTagForTag(tag: string): Promise<string>;
    getJoinedPonds(): Promise<Array<string>>;
    getLikeCountForPost(postId: string): Promise<bigint>;
    getLiliesByTag(tag: string, sortBy: string): Promise<Array<Post>>;
    getPond(name: string): Promise<Pond | null>;
    getPondAboutInfo(pondName: string): Promise<{
        title: string;
        associatedTags: Array<string>;
        admin: Principal;
        lilyCount: bigint;
        profileImage?: ExternalBlob;
        name: string;
        createdAt: bigint;
        memberCount: bigint;
        description: string;
        bannerImage?: ExternalBlob;
        moderators: Array<Principal>;
        visibility: Visibility;
        rules: Array<string>;
    } | null>;
    getPondModerators(pondName: string): Promise<Array<Principal>>;
    getPondRules(pondName: string): Promise<Array<string>>;
    getPost(id: string): Promise<Post | null>;
    getPostLikeCount(postId: string): Promise<bigint>;
    getRecentPosts(limit: bigint): Promise<Array<Activity>>;
    getRecentRibbitViews(username: string, limit: bigint): Promise<Array<Activity>>;
    getRecentRibbits(limit: bigint): Promise<Array<Activity>>;
    getRecentlyLikedPosts(limit: bigint): Promise<Array<Activity>>;
    getRibbit(id: string): Promise<Ribbit | null>;
    getRibbitCountForPost(postId: string): Promise<bigint>;
    getRibbitLikeCount(ribbitId: string): Promise<bigint>;
    getTagRedirects(): Promise<Array<[string, string]>>;
    getTagSuggestions(prefix: string, limit: bigint): Promise<Array<string>>;
    getThreadedRibbits(postId: string): Promise<Array<Ribbit>>;
    getUserAvatarByUsername(username: string): Promise<ExternalBlob | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getViewCountForPost(postId: string): Promise<bigint>;
    hasUserLikedPost(postId: string): Promise<boolean>;
    hasUserLikedRibbit(ribbitId: string): Promise<boolean>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isPondAdmin(pondName: string): Promise<boolean>;
    isUsernameAvailable(username: string): Promise<boolean>;
    joinPond(pondName: string): Promise<void>;
    leavePond(pondName: string): Promise<void>;
    likePost(postId: string): Promise<void>;
    likeRibbit(ribbitId: string): Promise<void>;
    listPonds(): Promise<Array<Pond>>;
    listPosts(): Promise<Array<Post>>;
    listRibbits(postId: string): Promise<Array<Ribbit>>;
    mergeSimilarTags(): Promise<void>;
    recordUsernameChange(username: string): Promise<void>;
    registerUsername(username: string): Promise<void>;
    releaseUsername(username: string): Promise<void>;
    removeMemberFromPond(pondName: string, member: Principal): Promise<void>;
    removeModerator(pondName: string, moderator: Principal): Promise<void>;
    removePondRule(pondName: string, rule: string): Promise<void>;
    saveAvatarByUsername(username: string, avatar: ExternalBlob): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchPonds(searchTerm: string): Promise<Array<Pond>>;
    searchPosts(searchTerm: string): Promise<Array<Post>>;
    unlikePost(postId: string): Promise<void>;
    unlikeRibbit(ribbitId: string): Promise<void>;
}
import type { Activity as _Activity, ActivityType as _ActivityType, ExternalBlob as _ExternalBlob, Pond as _Pond, Post as _Post, Ribbit as _Ribbit, UserProfile as _UserProfile, UserRole as _UserRole, Visibility as _Visibility, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addModerator(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addModerator(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addModerator(arg0, arg1);
            return result;
        }
    }
    async addPondRule(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPondRule(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPondRule(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async canChangeUsername(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.canChangeUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canChangeUsername(arg0);
            return result;
        }
    }
    async clearPostLikes(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearPostLikes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearPostLikes(arg0);
            return result;
        }
    }
    async createPond(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob, arg4: ExternalBlob, arg5: ExternalBlob, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPond(arg0, arg1, arg2, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg3), await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg4), await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPond(arg0, arg1, arg2, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg3), await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg4), await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async createPost(arg0: string, arg1: string, arg2: ExternalBlob | null, arg3: string | null, arg4: string, arg5: string, arg6: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1, await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1, await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async createRibbit(arg0: string, arg1: string | null, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createRibbit(arg0, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRibbit(arg0, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async deleteLily(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLily(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLily(arg0);
            return result;
        }
    }
    async deleteRibbit(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRibbit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRibbit(arg0);
            return result;
        }
    }
    async editPondSettings(arg0: string, arg1: string | null, arg2: string | null, arg3: Visibility | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editPondSettings(arg0, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editPondSettings(arg0, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async getAllRecentActivities(arg0: bigint): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecentActivities(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecentActivities(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCanonicalTagForTag(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanonicalTagForTag(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanonicalTagForTag(arg0);
            return result;
        }
    }
    async getJoinedPonds(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJoinedPonds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJoinedPonds();
            return result;
        }
    }
    async getLikeCountForPost(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLikeCountForPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLikeCountForPost(arg0);
            return result;
        }
    }
    async getLiliesByTag(arg0: string, arg1: string): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiliesByTag(arg0, arg1);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiliesByTag(arg0, arg1);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPond(arg0: string): Promise<Pond | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPond(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPond(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPondAboutInfo(arg0: string): Promise<{
        title: string;
        associatedTags: Array<string>;
        admin: Principal;
        lilyCount: bigint;
        profileImage?: ExternalBlob;
        name: string;
        createdAt: bigint;
        memberCount: bigint;
        description: string;
        bannerImage?: ExternalBlob;
        moderators: Array<Principal>;
        visibility: Visibility;
        rules: Array<string>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPondAboutInfo(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPondAboutInfo(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPondModerators(arg0: string): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPondModerators(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPondModerators(arg0);
            return result;
        }
    }
    async getPondRules(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPondRules(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPondRules(arg0);
            return result;
        }
    }
    async getPost(arg0: string): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostLikeCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostLikeCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostLikeCount(arg0);
            return result;
        }
    }
    async getRecentPosts(arg0: bigint): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentPosts(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentPosts(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentRibbitViews(arg0: string, arg1: bigint): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentRibbitViews(arg0, arg1);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentRibbitViews(arg0, arg1);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentRibbits(arg0: bigint): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentRibbits(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentRibbits(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentlyLikedPosts(arg0: bigint): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentlyLikedPosts(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentlyLikedPosts(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRibbit(arg0: string): Promise<Ribbit | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRibbit(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRibbit(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRibbitCountForPost(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRibbitCountForPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRibbitCountForPost(arg0);
            return result;
        }
    }
    async getRibbitLikeCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRibbitLikeCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRibbitLikeCount(arg0);
            return result;
        }
    }
    async getTagRedirects(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTagRedirects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTagRedirects();
            return result;
        }
    }
    async getTagSuggestions(arg0: string, arg1: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTagSuggestions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTagSuggestions(arg0, arg1);
            return result;
        }
    }
    async getThreadedRibbits(arg0: string): Promise<Array<Ribbit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getThreadedRibbits(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThreadedRibbits(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAvatarByUsername(arg0: string): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAvatarByUsername(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAvatarByUsername(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getViewCountForPost(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getViewCountForPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getViewCountForPost(arg0);
            return result;
        }
    }
    async hasUserLikedPost(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserLikedPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserLikedPost(arg0);
            return result;
        }
    }
    async hasUserLikedRibbit(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserLikedRibbit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserLikedRibbit(arg0);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isPondAdmin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPondAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPondAdmin(arg0);
            return result;
        }
    }
    async isUsernameAvailable(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUsernameAvailable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUsernameAvailable(arg0);
            return result;
        }
    }
    async joinPond(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinPond(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinPond(arg0);
            return result;
        }
    }
    async leavePond(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leavePond(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leavePond(arg0);
            return result;
        }
    }
    async likePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async likeRibbit(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeRibbit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeRibbit(arg0);
            return result;
        }
    }
    async listPonds(): Promise<Array<Pond>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPonds();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPonds();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPosts();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPosts();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRibbits(arg0: string): Promise<Array<Ribbit>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRibbits(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRibbits(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async mergeSimilarTags(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.mergeSimilarTags();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mergeSimilarTags();
            return result;
        }
    }
    async recordUsernameChange(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordUsernameChange(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordUsernameChange(arg0);
            return result;
        }
    }
    async registerUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUsername(arg0);
            return result;
        }
    }
    async releaseUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.releaseUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.releaseUsername(arg0);
            return result;
        }
    }
    async removeMemberFromPond(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMemberFromPond(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMemberFromPond(arg0, arg1);
            return result;
        }
    }
    async removeModerator(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeModerator(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeModerator(arg0, arg1);
            return result;
        }
    }
    async removePondRule(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePondRule(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePondRule(arg0, arg1);
            return result;
        }
    }
    async saveAvatarByUsername(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAvatarByUsername(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAvatarByUsername(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchPonds(arg0: string): Promise<Array<Pond>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPonds(arg0);
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPonds(arg0);
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchPosts(arg0: string): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPosts(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPosts(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async unlikePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return result;
        }
    }
    async unlikeRibbit(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikeRibbit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikeRibbit(arg0);
            return result;
        }
    }
}
function from_candid_ActivityType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityType): ActivityType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Activity_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Activity {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Pond_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Pond): Promise<Pond> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_Post_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Promise<Post> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Ribbit_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ribbit): Ribbit {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Visibility_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Visibility): Visibility {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Pond]): Promise<Pond | null> {
    return value.length === 0 ? null : await from_candid_Pond_n33(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        title: string;
        associatedTags: Array<string>;
        admin: Principal;
        lilyCount: bigint;
        profileImage: [] | [_ExternalBlob];
        name: string;
        createdAt: bigint;
        memberCount: bigint;
        description: string;
        bannerImage: [] | [_ExternalBlob];
        moderators: Array<Principal>;
        visibility: _Visibility;
        rules: Array<string>;
    }]): Promise<{
    title: string;
    associatedTags: Array<string>;
    admin: Principal;
    lilyCount: bigint;
    profileImage?: ExternalBlob;
    name: string;
    createdAt: bigint;
    memberCount: bigint;
    description: string;
    bannerImage?: ExternalBlob;
    moderators: Array<Principal>;
    visibility: Visibility;
    rules: Array<string>;
} | null> {
    return value.length === 0 ? null : await from_candid_record_n38(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Promise<Post | null> {
    return value.length === 0 ? null : await from_candid_Post_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Ribbit]): Ribbit | null {
    return value.length === 0 ? null : from_candid_Ribbit_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    username: string;
    pond: string;
    type: _ActivityType;
    timestamp: bigint;
    targetId: string;
}): {
    id: string;
    username: string;
    pond: string;
    type: ActivityType;
    timestamp: bigint;
    targetId: string;
} {
    return {
        id: value.id,
        username: value.username,
        pond: value.pond,
        type: from_candid_ActivityType_n19(_uploadFile, _downloadFile, value.type),
        timestamp: value.timestamp,
        targetId: value.targetId
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    joinedPonds: Array<string>;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    name: string;
    joinedPonds: Array<string>;
    avatar?: ExternalBlob;
}> {
    return {
        name: value.name,
        joinedPonds: value.joinedPonds,
        avatar: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.avatar))
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    tag: [] | [string];
    title: string;
    content: string;
    username: string;
    link: [] | [string];
    pond: string;
    viewCount: bigint;
    timestamp: bigint;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    tag?: string;
    title: string;
    content: string;
    username: string;
    link?: string;
    pond: string;
    viewCount: bigint;
    timestamp: bigint;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        tag: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.tag)),
        title: value.title,
        content: value.content,
        username: value.username,
        link: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.link)),
        pond: value.pond,
        viewCount: value.viewCount,
        timestamp: value.timestamp,
        image: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.image))
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    associatedTags: Array<string>;
    members: Array<Principal>;
    admin: Principal;
    lilyCount: bigint;
    profileImage: [] | [_ExternalBlob];
    name: string;
    createdAt: bigint;
    memberCount: bigint;
    description: string;
    bannerImage: [] | [_ExternalBlob];
    image: [] | [_ExternalBlob];
    moderators: Array<Principal>;
    visibility: _Visibility;
    rules: Array<string>;
}): Promise<{
    title: string;
    associatedTags: Array<string>;
    members: Array<Principal>;
    admin: Principal;
    lilyCount: bigint;
    profileImage?: ExternalBlob;
    name: string;
    createdAt: bigint;
    memberCount: bigint;
    description: string;
    bannerImage?: ExternalBlob;
    image?: ExternalBlob;
    moderators: Array<Principal>;
    visibility: Visibility;
    rules: Array<string>;
}> {
    return {
        title: value.title,
        associatedTags: value.associatedTags,
        members: value.members,
        admin: value.admin,
        lilyCount: value.lilyCount,
        profileImage: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.profileImage)),
        name: value.name,
        createdAt: value.createdAt,
        memberCount: value.memberCount,
        description: value.description,
        bannerImage: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.bannerImage)),
        image: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.image)),
        moderators: value.moderators,
        visibility: from_candid_Visibility_n35(_uploadFile, _downloadFile, value.visibility),
        rules: value.rules
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    associatedTags: Array<string>;
    admin: Principal;
    lilyCount: bigint;
    profileImage: [] | [_ExternalBlob];
    name: string;
    createdAt: bigint;
    memberCount: bigint;
    description: string;
    bannerImage: [] | [_ExternalBlob];
    moderators: Array<Principal>;
    visibility: _Visibility;
    rules: Array<string>;
}): Promise<{
    title: string;
    associatedTags: Array<string>;
    admin: Principal;
    lilyCount: bigint;
    profileImage?: ExternalBlob;
    name: string;
    createdAt: bigint;
    memberCount: bigint;
    description: string;
    bannerImage?: ExternalBlob;
    moderators: Array<Principal>;
    visibility: Visibility;
    rules: Array<string>;
}> {
    return {
        title: value.title,
        associatedTags: value.associatedTags,
        admin: value.admin,
        lilyCount: value.lilyCount,
        profileImage: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.profileImage)),
        name: value.name,
        createdAt: value.createdAt,
        memberCount: value.memberCount,
        description: value.description,
        bannerImage: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.bannerImage)),
        moderators: value.moderators,
        visibility: from_candid_Visibility_n35(_uploadFile, _downloadFile, value.visibility),
        rules: value.rules
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    username: string;
    timestamp: bigint;
    parentId: [] | [string];
    postId: string;
}): {
    id: string;
    content: string;
    username: string;
    timestamp: bigint;
    parentId?: string;
    postId: string;
} {
    return {
        id: value.id,
        content: value.content,
        username: value.username,
        timestamp: value.timestamp,
        parentId: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.parentId)),
        postId: value.postId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    like: null;
} | {
    post: null;
} | {
    ribbit: null;
} | {
    viewRibbit: null;
}): ActivityType {
    return "like" in value ? ActivityType.like : "post" in value ? ActivityType.post : "ribbit" in value ? ActivityType.ribbit : "viewRibbit" in value ? ActivityType.viewRibbit : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    privateVisibility: null;
} | {
    publicVisibility: null;
}): Visibility {
    return "privateVisibility" in value ? Visibility.privateVisibility : "publicVisibility" in value ? Visibility.publicVisibility : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Array<Activity> {
    return value.map((x)=>from_candid_Activity_n17(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Promise<Array<Post>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Post_n29(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ribbit>): Array<Ribbit> {
    return value.map((x)=>from_candid_Ribbit_n41(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Pond>): Promise<Array<Pond>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Pond_n33(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_UserProfile_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Visibility_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Visibility): _Visibility {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Visibility | null): [] | [_Visibility] {
    return value === null ? candid_none() : candid_some(to_candid_Visibility_n14(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    joinedPonds: Array<string>;
    avatar?: ExternalBlob;
}): Promise<{
    name: string;
    joinedPonds: Array<string>;
    avatar: [] | [_ExternalBlob];
}> {
    return {
        name: value.name,
        joinedPonds: value.joinedPonds,
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Visibility): {
    privateVisibility: null;
} | {
    publicVisibility: null;
} {
    return value == Visibility.privateVisibility ? {
        privateVisibility: null
    } : value == Visibility.publicVisibility ? {
        publicVisibility: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
